..\Debug\tojsstr.exe Globals.romdata  rom.dat       >  ..\..\deploy\js\romdata.js
..\Debug\tojsstr.exe Globals.romdata  fastrom.dat   >  ..\..\deploy\js\fastromdata.js

..\Debug\tojsstr.exe Globals.cartdata 3dczycst.bin  >  ..\..\deploy\js\roms\3dczycst.js
..\Debug\tojsstr.exe Globals.cartdata agt.bin       >  ..\..\deploy\js\roms\agt.js
..\Debug\tojsstr.exe Globals.cartdata armor.bin     >  ..\..\deploy\js\roms\armor.js
..\Debug\tojsstr.exe Globals.cartdata berzerk.bin   >  ..\..\deploy\js\roms\berzerk.js
..\Debug\tojsstr.exe Globals.cartdata bedlam.bin    >  ..\..\deploy\js\roms\bedlam.js
..\Debug\tojsstr.exe Globals.cartdata blitz.bin     >  ..\..\deploy\js\roms\blitz.js
..\Debug\tojsstr.exe Globals.cartdata castle.bin    >  ..\..\deploy\js\roms\castle.js
..\Debug\tojsstr.exe Globals.cartdata chasm.bin     >  ..\..\deploy\js\roms\chasm.js
..\Debug\tojsstr.exe Globals.cartdata dktower.bin   >  ..\..\deploy\js\roms\dktower.js
..\Debug\tojsstr.exe Globals.cartdata frogger.bin   >  ..\..\deploy\js\roms\frogger.js
..\Debug\tojsstr.exe Globals.cartdata gravplus.bin  >  ..\..\deploy\js\roms\gravplus.js
..\Debug\tojsstr.exe Globals.cartdata headsup.bin   >  ..\..\deploy\js\roms\headsup.js
..\Debug\tojsstr.exe Globals.cartdata hyper.bin     >  ..\..\deploy\js\roms\hyper.js
..\Debug\tojsstr.exe Globals.cartdata MailPlane.BIN >  ..\..\deploy\js\roms\MailPlane.js
..\Debug\tojsstr.exe Globals.cartdata mine3.bin     >  ..\..\deploy\js\roms\mine3.js
..\Debug\tojsstr.exe Globals.cartdata minestorm.bin >  ..\..\deploy\js\roms\minestorm.js
..\Debug\tojsstr.exe Globals.cartdata moon.bin      >  ..\..\deploy\js\roms\moon.js
..\Debug\tojsstr.exe Globals.cartdata mstorm2.bin   >  ..\..\deploy\js\roms\mstorm2.js
..\Debug\tojsstr.exe Globals.cartdata narzod.bin    >  ..\..\deploy\js\roms\narzod.js
..\Debug\tojsstr.exe Globals.cartdata nebula.bin    >  ..\..\deploy\js\roms\nebula.js
..\Debug\tojsstr.exe Globals.cartdata Omega16k.bin  >  ..\..\deploy\js\roms\Omega16k.js
..\Debug\tojsstr.exe Globals.cartdata Pitchers.bin  >  ..\..\deploy\js\roms\Pitchers.js
..\Debug\tojsstr.exe Globals.cartdata patriot.bin   >  ..\..\deploy\js\roms\patriot.js
..\Debug\tojsstr.exe Globals.cartdata polar.bin     >  ..\..\deploy\js\roms\polar.js
..\Debug\tojsstr.exe Globals.cartdata pole.bin      >  ..\..\deploy\js\roms\pole.js
..\Debug\tojsstr.exe Globals.cartdata revector.bin  >  ..\..\deploy\js\roms\revector.js
..\Debug\tojsstr.exe Globals.cartdata ripoff.bin    >  ..\..\deploy\js\roms\ripoff.js
..\Debug\tojsstr.exe Globals.cartdata rocks.bin     >  ..\..\deploy\js\roms\rocks.js
..\Debug\tojsstr.exe Globals.cartdata scramble.bin  >  ..\..\deploy\js\roms\scramble.js
..\Debug\tojsstr.exe Globals.cartdata sfpd.bin      >  ..\..\deploy\js\roms\sfpd.js
..\Debug\tojsstr.exe Globals.cartdata solar.bin     >  ..\..\deploy\js\roms\solar.js
..\Debug\tojsstr.exe Globals.cartdata spike.bin     >  ..\..\deploy\js\roms\spike.js
..\Debug\tojsstr.exe Globals.cartdata spikehop.bin  >  ..\..\deploy\js\roms\spikehop.js
..\Debug\tojsstr.exe Globals.cartdata spikewater.bin>  ..\..\deploy\js\roms\spikewater.js
..\Debug\tojsstr.exe Globals.cartdata space.bin     >  ..\..\deploy\js\roms\space.js
..\Debug\tojsstr.exe Globals.cartdata spinball.bin  >  ..\..\deploy\js\roms\spinball.js
..\Debug\tojsstr.exe Globals.cartdata starhawk.bin  >  ..\..\deploy\js\roms\starhawk.js
..\Debug\tojsstr.exe Globals.cartdata startrek.bin  >  ..\..\deploy\js\roms\startrek.js
..\Debug\tojsstr.exe Globals.cartdata sweep.bin     >  ..\..\deploy\js\roms\sweep.js
..\Debug\tojsstr.exe Globals.cartdata tdf.bin       >  ..\..\deploy\js\roms\tdf.js
..\Debug\tojsstr.exe Globals.cartdata thrust.bin    >  ..\..\deploy\js\roms\thrust.js
..\Debug\tojsstr.exe Globals.cartdata tsu-dl.bin    >  ..\..\deploy\js\roms\tsu.js
..\Debug\tojsstr.exe Globals.cartdata vecmania1.bin >  ..\..\deploy\js\roms\vecmania1.js
..\Debug\tojsstr.exe Globals.cartdata vecmania2.bin >  ..\..\deploy\js\roms\vecmania2.js
..\Debug\tojsstr.exe Globals.cartdata vix-dl.bin    >  ..\..\deploy\js\roms\vix.js
..\Debug\tojsstr.exe Globals.cartdata webwars.bin   >  ..\..\deploy\js\roms\webwars.js
..\Debug\tojsstr.exe Globals.cartdata wotr.bin      >  ..\..\deploy\js\roms\wotr.js
